## Import libraries

In [41]:
import numpy as np
import pandas as pd

## Load dataset

In [2]:
raw_data = pd.read_csv('Data.csv')

In [3]:
df = raw_data.copy()

df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

## Dealing with missing values and Replacing text with number

In [34]:
df['experience'] = df['experience'].fillna('zero')

df['experience'] = df['experience'].map({'zero': 0, 'two': 2, 'three': 3, 'five': 5, 'seven':7 , 'ten': 10, 'eleven': 11})

In [6]:
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(0)#.apply(np.int64)

df['test_score(out of 10)'] = df['test_score(out of 10)'].replace(0,df['test_score(out of 10)'].median ())

df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.5                           7      72000
7          11                    7.0                           8      80000

## Create x, y

In [12]:
x = df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']]

y = df['salary($)']

## Splitting into training set and test set

In [13]:
from sklearn.model_selection import train_test_split
 
x_train, x_test, y_train, y_test = train_test_split (x, y, test_size = 0.2, random_state = 3)

C:\Users\hzfar\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


## Fitting Linear Regression to the training set

In [20]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(x_train,y_train)

LinearRegression()

## Predicting the testset results


In [30]:
y_pred = reg.predict(x_test)
y_pred

array([59353.54850161, 78199.8284176 ])

## Predict salary for 2 yr experience, 9 test score, 6 interview score

In [28]:
reg.predict([[2,9,6]])

array([54287.00411206])

## Predict salary for 12 yr experience, 10 test score, 10 interview score

In [29]:
reg.predict([[12,10,10]])

array([91778.96636393])